// File generated by FlutterFire CLI / manual Firebase configuration
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(765

/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyqRt4vQPuV4MYmfIFfkv2xBiwIxh-H_s',
    appId: '1:537285994094:web:0adb968e133093ed3da87f',
    messagingSenderId: '537285994094',
    projectId: 'buku-kontak-de825',
    authDomain: 'buku-kontak-de825.firebaseapp.com',
    storageBucket: 'buku-kontak-de825.firebasestorage.app',
    measurementId: 'G-BD7560N70H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEBGdkiH-MxYxf1laClzfVXgkN8UmNMrY',
    appId: '1:537285994094:android:c71583f1eb5c09fe3da87f',
    messagingSenderId: '537285994094',
    projectId: 'buku-kontak-de825',
    storageBucket: 'buku-kontak-de825.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXfXrRbmzPoNVvPAbWdO7meQnAj_yko1g',
    appId: '1:537285994094:ios:884fdbccb2668bef3da87f',
    messagingSenderId: '537285994094',
    projectId: 'buku-kontak-de825',
    storageBucket: 'buku-kontak-de825.firebasestorage.app',
    iosBundleId: 'com.example.materialDesign',
  );
}
